server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 657445791412-3p6k50aqfaifqpfdho917k565k735c2d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 653994566680384
            client-secret: 2fc15f8a6065db1e2f61c2d1af407f96
            scope:
              - email
              - public_profile